add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[ğŸ›¸â¯](fg:#00BBC0)"
error_symbol = "[ğŸ›¸â¯](fg:red)"

[directory]
style = "bold fg:244"
read_only = " ğŸ” "
truncation_length = 4
truncate_to_repo = false
home_symbol = "~â›º"

[nodejs]
disabled = true

[java]
disabled=true